import { buildGraph } from "./build";
import type { LevelDef, SheafGraph } from "./types";

const LEVELS: LevelDef[] = [
  {
    id: 0,
    code: "L0",
    label: "Authors",
    kicker: "Boundary",
    blurb: "Known embeddings. Harmonic extension is not allowed to move them.",
  },
  {
    id: 1,
    code: "L1",
    label: "Sheaf objects",
    kicker: "The paper",
    blurb: "Cellular sheaf, Laplacian, energy — the closed vocabulary of arXiv:2309.03773.",
  },
  {
    id: 2,
    code: "L2",
    label: "Algorithms",
    kicker: "Unknowns",
    blurb: "Harmonic extension, Euler scheme, iterative propagation — inferred by descent.",
  },
  {
    id: 3,
    code: "L3",
    label: "Models",
    kicker: "TransE special case",
    blurb: "Identity restrictions, translation vectors. Closed form (Thm 3.1) is the ground truth.",
  },
];

/** Paper-derived TransE sheaf from Cobb & Gebhart + the hybrid_sheaf_memory demo. */
export function cobbGraph(): SheafGraph {
  return buildGraph(
    "cobb",
    "Cobb–Gebhart seed graph",
    "TransE sheaf · Thm 3.1 / 3.2",
    "Real sample from Feature Propagation on Knowledge Graphs Using Cellular Sheaves (arXiv:2309.03773). Identity restrictions, dim 4, translation vectors. Unknowns are harmonic-extended; known authors stay pinned.",
    LEVELS,
    [
      {
        id: "Cobb",
        title: "Cobb",
        kind: "paper",
        level: 0,
        dim: 4,
        known: true,
        summary: "J. Cobb. Co-author of the feature-propagation paper. Boundary stalk.",
        sources: ["S4"],
        arxiv: "2309.03773",
      },
      {
        id: "Gebhart",
        title: "Gebhart",
        kind: "paper",
        level: 0,
        dim: 4,
        known: true,
        summary: "T. Gebhart. Co-author. Boundary stalk — must not drift under Euler iteration.",
        sources: ["S4"],
      },
      {
        id: "CellularSheaf",
        title: "Cellular sheaf",
        kind: "concept",
        level: 1,
        dim: 4,
        known: true,
        summary: "The paper's base object. Identity restriction maps recover TransE.",
        sources: ["S4"],
      },
      {
        id: "SheafLaplacian",
        title: "Sheaf Laplacian",
        kind: "concept",
        level: 1,
        dim: 4,
        known: true,
        summary: "L_F = δᵀδ. For TransE, Δ = L ⊗ I_d so the closed form is one |U|×|U| scalar system reused across dimensions.",
        sources: ["S4"],
      },
      {
        id: "DirichletEnergy",
        title: "Dirichlet energy",
        kind: "concept",
        level: 1,
        dim: 4,
        known: true,
        summary: "E = Σ ‖x_h + r − x_t‖². The quantity Diffuse Sections minimises.",
        sources: ["S4"],
      },
      {
        id: "HarmonicExtension",
        title: "Harmonic extension",
        kind: "algorithm",
        level: 2,
        dim: 4,
        summary: "Unknown in the seed graph. Inferred by Thm 3.1 / iterative Euler. Uses the Laplacian, minimises energy.",
        sources: ["S4"],
      },
      {
        id: "EulerScheme",
        title: "Euler scheme",
        kind: "algorithm",
        level: 2,
        dim: 4,
        summary: "Thm 3.2 discretisation of sheaf-Laplacian gradient flow. Degree-normalised, h ≤ 1 converges.",
        sources: ["S4"],
      },
      {
        id: "IterativePropagation",
        title: "Iterative propagation",
        kind: "algorithm",
        level: 2,
        dim: 4,
        summary: "Message-passing form of the Euler scheme. No dense matrix.",
        sources: ["S4"],
      },
      {
        id: "TransE",
        title: "TransE",
        kind: "model",
        level: 3,
        dim: 4,
        known: true,
        summary: "Identity-restriction special case. Closed-form solver in this explorer is exact for this subgraph.",
        sources: ["S4"],
      },
      {
        id: "KnowledgeGraph",
        title: "Knowledge graph",
        kind: "concept",
        level: 3,
        dim: 4,
        known: true,
        summary: "Domain of the embedding. TransE is_a KnowledgeGraph model in the seed.",
        sources: ["S4"],
      },
      {
        id: "MultigridVCycle",
        title: "Multigrid V-cycle",
        kind: "algorithm",
        level: 2,
        dim: 4,
        summary: "Two-level correction on cluster indicators. Coarse solve moves subspaces rigidly; smoother restores local consistency.",
        sources: ["S4"],
      },
      {
        id: "ClusterPartition",
        title: "Cluster partition",
        kind: "concept",
        level: 3,
        dim: 4,
        summary: "Hierarchy used by HiSP-style pooling and the V-cycle coarse space.",
        sources: ["S4"],
      },
    ],
    [
      { source: "Cobb", target: "CellularSheaf", relation: "authored", restrictKind: "identity", translationScale: 0.08 },
      { source: "Gebhart", target: "CellularSheaf", relation: "authored", restrictKind: "identity", translationScale: 0.08 },
      { source: "CellularSheaf", target: "SheafLaplacian", relation: "defines", restrictKind: "identity", translationScale: 0.06 },
      { source: "SheafLaplacian", target: "DirichletEnergy", relation: "defines", restrictKind: "identity", translationScale: 0.06 },
      { source: "HarmonicExtension", target: "DirichletEnergy", relation: "minimizes", restrictKind: "identity", translationScale: 0.05 },
      { source: "HarmonicExtension", target: "SheafLaplacian", relation: "uses", restrictKind: "identity", translationScale: 0.05 },
      { source: "CellularSheaf", target: "HarmonicExtension", relation: "enables", restrictKind: "identity", translationScale: 0.07 },
      { source: "HarmonicExtension", target: "EulerScheme", relation: "uses", restrictKind: "identity", translationScale: 0.05 },
      { source: "EulerScheme", target: "IterativePropagation", relation: "is_a", restrictKind: "identity", translationScale: 0.04 },
      { source: "IterativePropagation", target: "DirichletEnergy", relation: "minimizes", restrictKind: "identity", translationScale: 0.05 },
      { source: "TransE", target: "KnowledgeGraph", relation: "is_a", restrictKind: "identity", translationScale: 0.04 },
      { source: "MultigridVCycle", target: "EulerScheme", relation: "uses", restrictKind: "identity", translationScale: 0.05 },
      { source: "MultigridVCycle", target: "ClusterPartition", relation: "uses", restrictKind: "identity", translationScale: 0.05 },
      { source: "TransE", target: "CellularSheaf", relation: "is_a", restrictKind: "identity", translationScale: 0.05 },
    ],
  );
}
