import { buildGraph, type EdgeSpec, type NodeSpec } from "./build";
import type { LevelDef, SheafGraph } from "./types";

const LEVELS: LevelDef[] = [
  {
    id: 0,
    code: "L0",
    label: "Foundations",
    kicker: "Cells, stalks, coboundary",
    blurb: "A cellular sheaf assigns a vector space to every cell and a linear map to every incidence. Agreement is a kernel.",
  },
  {
    id: 1,
    code: "L1",
    label: "Sheaf theory",
    kicker: "Restriction geometry",
    blurb: "Restriction maps encode structural priors. Variable-dimension stalks refuse a forced ambient space.",
  },
  {
    id: 2,
    code: "L2",
    label: "Applications",
    kicker: "KGE, HiSP, diffusion",
    blurb: "Knowledge-graph embedding, neural sheaf diffusion, and hierarchical pooling as live operators on the same Laplacian.",
  },
  {
    id: 3,
    code: "L3",
    label: "Viz & integrity",
    kicker: "Residuals as data",
    blurb: "Dirichlet energy is a first-class visual variable. Only approximate global sections survive as trusted knowledge.",
  },
];

const N: NodeSpec[] = [
  {
    id: "cellular-sheaf",
    title: "Cellular sheaf",
    kind: "concept",
    level: 0,
    dim: 6,
    known: true,
    summary:
      "A sheaf F on a graph G: a stalk (vector space) on every vertex and edge, plus a linear restriction F_{v◃e}: F(v)→F(e) for each incidence. Minimal structure for local data plus comparison rules.",
    sources: ["S4", "S2"],
    aliases: ["sheaf on a graph", "F"],
  },
  {
    id: "stalk",
    title: "Stalk F(v)",
    kind: "concept",
    level: 0,
    dim: 8,
    known: true,
    summary:
      "The vector space assigned to a cell. Vertex stalks hold an entity's private state; edge stalks hold the space in which two entities are allowed to compare. Dims here range from 2 to 16 — no forced common ambient dimension.",
    sources: ["S4"],
  },
  {
    id: "restriction-map",
    title: "Restriction map",
    kind: "concept",
    level: 0,
    dim: 5,
    known: true,
    summary:
      "Linear map F_{v◃e}: F(v) → F(e). Selects, rotates, projects, or embeds what a node may say on a given channel. Identity, projection, embed, spectral, and type-aware maps are all first-class here.",
    sources: ["S4", "S18"],
  },
  {
    id: "coboundary",
    title: "Coboundary δ_F",
    kind: "concept",
    level: 0,
    dim: 6,
    known: true,
    summary:
      "δx = F_{v◃e} x_v − F_{u◃e} x_u. The disagreement of a 0-cochain across every edge, after both stalks have been mapped into the edge space. Its kernel is the space of global sections.",
    sources: ["S4"],
  },
  {
    id: "sheaf-laplacian",
    title: "Sheaf Laplacian L_F",
    kind: "concept",
    level: 0,
    dim: 8,
    known: true,
    summary:
      "L_F = δ_F^T δ_F. Quadratic form xᵀ L_F x is the Dirichlet energy. Kernel is H⁰. Spectral gap sets how fast diffusion contracts. Lower energy equals higher probability of truth.",
    sources: ["S4"],
  },
  {
    id: "dirichlet-energy",
    title: "Dirichlet energy",
    kind: "concept",
    level: 0,
    dim: 4,
    known: true,
    summary:
      "E(x) = Σ_e ‖F_s x_s − F_t x_t − r_e‖². Zero energy is a global section. The visual layer maps this residual to emerald → ochre → rose on every edge.",
    sources: ["S4", "S5"],
  },
  {
    id: "global-section",
    title: "Global section",
    kind: "concept",
    level: 0,
    dim: 5,
    known: true,
    summary:
      "An assignment of stalk values that agrees on every restriction (δx = 0). Coordination, consensus, and 'true facts' in the sheaf-KGE reading are all: find a global section.",
    sources: ["S4", "S2"],
  },
  {
    id: "cohomology",
    title: "Sheaf cohomology",
    kind: "concept",
    level: 0,
    dim: 7,
    known: true,
    summary:
      "H⁰ is agreement; H¹ is obstruction. Non-vanishing H¹ is a contradiction no single node can locally see. Residuals of L_F are a computable proxy for that obstruction.",
    sources: ["S4", "S5"],
  },
  {
    id: "zero-cochain",
    title: "0-cochain",
    kind: "concept",
    level: 0,
    dim: 10,
    summary:
      "The space of all entity embeddings before consistency is enforced. A knowledge sheaf plus a 0-cochain pulled back along the schema is the sheaf embedding.",
    sources: ["S4"],
  },
  {
    id: "hansen-ghrist",
    title: "Spectral Theory of Cellular Sheaves",
    kind: "paper",
    level: 0,
    dim: 4,
    known: true,
    arxiv: "1808.01513",
    summary:
      "Hansen & Ghrist, arXiv:1808.01513. Laplacian, energy, harmonic representatives. Every later coordination and KGE sheaf paper sits on this spectral theory.",
    sources: ["S4"],
  },

  {
    id: "knowledge-sheaf",
    title: "Knowledge sheaf",
    kind: "concept",
    level: 1,
    dim: 9,
    summary:
      "A sheaf defined on a schema Q, pulled back to a knowledge graph G. An embedding is no longer a list of raw vectors — it is (F, x) where x is a 0-cochain.",
    sources: ["S4"],
    aliases: ["sheaf embedding"],
  },
  {
    id: "schema-q",
    title: "Schema Q",
    kind: "concept",
    level: 1,
    dim: 5,
    known: true,
    summary:
      "The genetic blueprint: allowed entity types and the relations permitted between them. The messy graph G is instantiated by pulling Q back, so local structure replicates across entities.",
    sources: ["S4"],
  },
  {
    id: "pullback",
    title: "Pullback G ← Q",
    kind: "concept",
    level: 1,
    dim: 6,
    summary:
      "Instantiating reality: local sheaf structure on the schema is copied onto every matching subgraph of G. Restriction maps travel with the types.",
    sources: ["S4"],
  },
  {
    id: "transe",
    title: "TransE",
    kind: "model",
    level: 1,
    dim: 4,
    known: true,
    summary:
      "Translation model x_h + r ≈ x_t. The identity-restriction special case of the sheaf Laplacian (Cobb & Gebhart Eq. 4). E = Σ ‖x_h + r − x_t‖².",
    sources: ["S4"],
  },
  {
    id: "rotate",
    title: "RotatE",
    kind: "model",
    level: 1,
    dim: 6,
    known: true,
    summary:
      "Relations as rotations in complex space. A sheaf with orthogonal restriction maps of equal dimension — F_{h◃r} is a rotation, F_{t◃r} is identity.",
    sources: ["S4"],
  },
  {
    id: "complex",
    title: "ComplEx",
    kind: "model",
    level: 1,
    dim: 6,
    summary:
      "Hermitian inner-product scoring. Lives in the fragmented KGE taxonomy the sheaf lens unifies: each model is a choice of restriction maps, not a new geometry.",
    sources: ["S4"],
  },
  {
    id: "structured-embedding",
    title: "Structured Embedding",
    kind: "model",
    level: 1,
    dim: 8,
    summary:
      "SE: two matrices per relation, W_h x_h ≈ W_t x_t. Exactly a pair of restriction maps into an edge stalk. The sheaf reading makes this the generic case.",
    sources: ["S4"],
  },
  {
    id: "cobb-gebhart",
    title: "Feature Propagation on KGs",
    kind: "paper",
    level: 1,
    dim: 5,
    known: true,
    arxiv: "2309.03773",
    summary:
      "Cobb & Gebhart, arXiv:2309.03773. Cellular sheaves on knowledge graphs; closed-form harmonic extension (Thm 3.1) and iterative Euler scheme (Thm 3.2). The numerical engine of this explorer.",
    sources: ["S4"],
  },
  {
    id: "harmonic-extension",
    title: "Harmonic extension",
    kind: "algorithm",
    level: 1,
    dim: 7,
    summary:
      "Fix known (boundary) stalks, solve L[U,U] X_U = b_U − L[U,B] X_B. New facts integrate without retraining. Unknown entities are inferred by energy minimisation.",
    sources: ["S4", "S5"],
  },
  {
    id: "multi-dim-stalks",
    title: "Novel multi-dim stalks",
    kind: "concept",
    level: 1,
    dim: 16,
    summary:
      "Every node owns its own finite-dimensional vector space (dims 2–16). No forced common ambient dimension. Restriction maps of varying rank glue them. This is the representation, not a visualisation trick.",
    sources: ["S4"],
    aliases: ["variable-dimension stalks"],
  },
  {
    id: "feature-propagation",
    title: "Feature propagation",
    kind: "algorithm",
    level: 1,
    dim: 6,
    summary:
      "Sheaf diffusion of node features across the knowledge graph. Message-passing gradients of the Dirichlet energy — no dense Laplacian materialised.",
    sources: ["S4"],
  },
  {
    id: "structural-priors",
    title: "Structural priors",
    kind: "concept",
    level: 1,
    dim: 5,
    summary:
      "Symmetric (F_h = F_t), orthogonal (rotations), dimensional reduction (dim F(r) < dim F(h)). Tweaking restriction maps dictates the logical rules of a relation.",
    sources: ["S4"],
  },

  {
    id: "kg-embedding",
    title: "Knowledge graph embedding",
    kind: "concept",
    level: 2,
    dim: 8,
    known: true,
    summary:
      "Translate discrete triples into continuous vector spaces so algorithms can predict the unknown. The sheaf lens unifies TransE, RotatE, ComplEx, SE as choices of F.",
    sources: ["S4"],
  },
  {
    id: "knowledge-graph",
    title: "Knowledge graph",
    kind: "concept",
    level: 2,
    dim: 4,
    known: true,
    summary:
      "Entities and typed relations. In the sheaf reading, G is the base space; the interesting data lives in the stalks and the restriction maps, not in the adjacency alone.",
    sources: ["S4"],
  },
  {
    id: "neural-sheaf-diffusion",
    title: "Neural Sheaf Diffusion",
    kind: "paper",
    level: 2,
    dim: 7,
    known: true,
    arxiv: "2202.04579",
    summary:
      "Bodnar, Di Giovanni, Chamberlain, Liò, Bronstein. NeurIPS 2022. Restriction maps are learned. Sheaf diffusion as a GNN layer that can break heterophily.",
    sources: ["S15"],
  },
  {
    id: "hisp",
    title: "HiSP pooling",
    kind: "algorithm",
    level: 2,
    dim: 9,
    summary:
      "Hierarchical Sheaf Pool: coarsen the complex while conserving low-frequency / harmonic modes. Galerkin projection of the sheaf Laplacian onto cluster indicators. Live operator in this explorer.",
    sources: ["S15"],
  },
  {
    id: "hetsheaf",
    title: "HETSHEAF",
    kind: "model",
    level: 2,
    dim: 8,
    summary:
      "Heterogeneous sheaf networks: type-aware restriction maps so different entity types keep their own stalk dimensions. The type-aware maps in this lattice are the toy version.",
    sources: ["S15"],
  },
  {
    id: "persistent-sheaf",
    title: "Persistent sheaf Laplacian",
    kind: "concept",
    level: 2,
    dim: 7,
    summary:
      "A filtration of sheaves yields a sequence of Laplacians whose spectra track when consistency appears or dies. Integrity as a persistence diagram.",
    sources: ["S4"],
  },
  {
    id: "coordination-sheaf",
    title: "Coordination sheaf",
    kind: "concept",
    level: 2,
    dim: 6,
    known: true,
    summary:
      "Triple (G, F, {U_e}): graph, cellular sheaf, convex edge potentials. Consensus, formation and flocking are the same algorithm with different F and U. Hanks et al., arXiv:2504.02049.",
    sources: ["S2"],
  },
  {
    id: "sheaf-diffusion",
    title: "Sheaf diffusion",
    kind: "algorithm",
    level: 2,
    dim: 5,
    summary:
      "Gradient flow on disagreement: x ← x − γ L_F x. Local: an agent needs only neighbours' restricted states. Diffuse Sections in this UI is that Euler step.",
    sources: ["S2", "S4"],
  },
  {
    id: "discourse-sheaf",
    title: "Discourse sheaf",
    kind: "concept",
    level: 2,
    dim: 6,
    summary:
      "Hansen & Ghrist: vertex stalk is private belief, restriction is the expression map. Public agreement is agreement of images, not of beliefs. Manufactured consensus is visible as residual.",
    sources: ["S5"],
    arxiv: "2005.12798",
  },
  {
    id: "learning-restriction",
    title: "Learning restriction maps",
    kind: "algorithm",
    level: 2,
    dim: 7,
    summary:
      "Di Nino, Barbarossa, Di Lorenzo, ICASSP 2025. Optimise F itself, not only x. A learned sheaf is powerful and, unless audited, unauditable.",
    sources: ["S18"],
    arxiv: "2501.19207",
  },

  {
    id: "bertin",
    title: "Bertin encoding",
    kind: "integrity",
    level: 3,
    dim: 3,
    known: true,
    summary:
      "Size and value for quantitative residual and stalk dim; position + ordered hue for hierarchy. No rainbow, no false-order traps. The lattice itself is the explanation.",
    sources: ["S4"],
  },
  {
    id: "residual-encoding",
    title: "Residual encoding",
    kind: "integrity",
    level: 3,
    dim: 4,
    summary:
      "Edge colour and thickness encode ‖δx_e‖. Emerald is local consistency; ochre is tension; rose is noise. Filter Noise hides the rose band so approximate global sections remain.",
    sources: ["S4"],
  },
  {
    id: "integrity-cohomology",
    title: "Integrity via cohomology",
    kind: "integrity",
    level: 3,
    dim: 6,
    summary:
      "Data integrity is not a score bolted on afterwards. It is H⁰ / H¹ of the sheaf. Trusted knowledge is the approximate kernel of L_F.",
    sources: ["S4", "S5"],
  },
  {
    id: "approx-sections",
    title: "Approximate global sections",
    kind: "integrity",
    level: 3,
    dim: 5,
    summary:
      "Perfect global sections are rare. We keep facts whose residual sits below a threshold and treat the rest as noise. Lower energy, higher probability of truth.",
    sources: ["S4"],
  },
  {
    id: "filter-noise",
    title: "Filter noise",
    kind: "integrity",
    level: 3,
    dim: 3,
    summary:
      "High-residual edges are the visual complement of H¹. Hiding them is a cohomology-informed filter, not a cosmetic declutter.",
    sources: ["S4"],
  },
  {
    id: "hierarchical-pool-op",
    title: "Hierarchical pool",
    kind: "algorithm",
    level: 3,
    dim: 8,
    summary:
      "Live HiSP-style coarsening. Cluster interiors are eliminated; the supernode stalk is a projection of the members. Complexity drops, harmonic structure is conserved.",
    sources: ["S15"],
  },
  {
    id: "consistency-radius",
    title: "Consistency radius",
    kind: "integrity",
    level: 3,
    dim: 4,
    summary:
      "Robinson: the smallest scale at which a sheaf assignment becomes inconsistent. In this lattice, the residual of an edge is that radius, localised.",
    sources: ["S7", "S8"],
  },
];

const E: EdgeSpec[] = [
  { source: "hansen-ghrist", target: "cellular-sheaf", relation: "defines" },
  { source: "hansen-ghrist", target: "sheaf-laplacian", relation: "defines" },
  { source: "cellular-sheaf", target: "stalk", relation: "defines" },
  { source: "cellular-sheaf", target: "restriction-map", relation: "defines" },
  { source: "cellular-sheaf", target: "coboundary", relation: "defines" },
  { source: "stalk", target: "restriction-map", relation: "uses" },
  { source: "restriction-map", target: "coboundary", relation: "uses" },
  { source: "coboundary", target: "sheaf-laplacian", relation: "defines" },
  { source: "sheaf-laplacian", target: "dirichlet-energy", relation: "defines" },
  { source: "coboundary", target: "global-section", relation: "defines" },
  { source: "sheaf-laplacian", target: "cohomology", relation: "uses" },
  { source: "global-section", target: "cohomology", relation: "part_of" },
  { source: "zero-cochain", target: "stalk", relation: "is_a" },
  { source: "zero-cochain", target: "dirichlet-energy", relation: "uses" },

  { source: "knowledge-sheaf", target: "cellular-sheaf", relation: "extends" },
  { source: "knowledge-sheaf", target: "schema-q", relation: "uses" },
  { source: "pullback", target: "schema-q", relation: "uses" },
  { source: "pullback", target: "knowledge-graph", relation: "uses" },
  { source: "knowledge-sheaf", target: "zero-cochain", relation: "uses" },
  { source: "transe", target: "restriction-map", relation: "is_a", note: "Identity restrictions." },
  { source: "rotate", target: "restriction-map", relation: "is_a", note: "Orthogonal restrictions." },
  { source: "structured-embedding", target: "restriction-map", relation: "is_a" },
  { source: "complex", target: "kg-embedding", relation: "is_a" },
  { source: "transe", target: "kg-embedding", relation: "is_a" },
  { source: "rotate", target: "kg-embedding", relation: "is_a" },
  { source: "structured-embedding", target: "kg-embedding", relation: "is_a" },
  { source: "cobb-gebhart", target: "harmonic-extension", relation: "defines" },
  { source: "cobb-gebhart", target: "feature-propagation", relation: "defines" },
  { source: "cobb-gebhart", target: "cellular-sheaf", relation: "uses" },
  { source: "harmonic-extension", target: "dirichlet-energy", relation: "minimizes" },
  { source: "harmonic-extension", target: "sheaf-laplacian", relation: "uses" },
  { source: "feature-propagation", target: "sheaf-diffusion", relation: "is_a" },
  { source: "multi-dim-stalks", target: "stalk", relation: "extends" },
  { source: "multi-dim-stalks", target: "restriction-map", relation: "uses" },
  { source: "structural-priors", target: "restriction-map", relation: "defines" },
  { source: "structural-priors", target: "transe", relation: "uses" },
  { source: "structural-priors", target: "rotate", relation: "uses" },

  { source: "kg-embedding", target: "knowledge-graph", relation: "uses" },
  { source: "neural-sheaf-diffusion", target: "sheaf-diffusion", relation: "extends" },
  { source: "neural-sheaf-diffusion", target: "restriction-map", relation: "uses" },
  { source: "hisp", target: "sheaf-laplacian", relation: "uses" },
  { source: "hisp", target: "neural-sheaf-diffusion", relation: "uses" },
  { source: "hetsheaf", target: "multi-dim-stalks", relation: "uses" },
  { source: "hetsheaf", target: "neural-sheaf-diffusion", relation: "extends" },
  { source: "persistent-sheaf", target: "sheaf-laplacian", relation: "extends" },
  { source: "coordination-sheaf", target: "cellular-sheaf", relation: "extends" },
  { source: "coordination-sheaf", target: "sheaf-diffusion", relation: "uses" },
  { source: "sheaf-diffusion", target: "sheaf-laplacian", relation: "uses" },
  { source: "sheaf-diffusion", target: "dirichlet-energy", relation: "minimizes" },
  { source: "discourse-sheaf", target: "cellular-sheaf", relation: "is_a" },
  { source: "discourse-sheaf", target: "restriction-map", relation: "uses" },
  { source: "learning-restriction", target: "restriction-map", relation: "uses" },
  { source: "learning-restriction", target: "neural-sheaf-diffusion", relation: "related_to" },
  { source: "knowledge-graph", target: "cellular-sheaf", relation: "uses" },

  { source: "bertin", target: "residual-encoding", relation: "defines" },
  { source: "residual-encoding", target: "dirichlet-energy", relation: "uses" },
  { source: "integrity-cohomology", target: "cohomology", relation: "uses" },
  { source: "integrity-cohomology", target: "approx-sections", relation: "defines" },
  { source: "approx-sections", target: "global-section", relation: "is_a" },
  { source: "filter-noise", target: "residual-encoding", relation: "uses" },
  { source: "filter-noise", target: "approx-sections", relation: "uses" },
  { source: "hierarchical-pool-op", target: "hisp", relation: "implements" },
  { source: "hierarchical-pool-op", target: "sheaf-laplacian", relation: "uses" },
  { source: "consistency-radius", target: "integrity-cohomology", relation: "related_to" },
  { source: "bertin", target: "multi-dim-stalks", relation: "uses" },
  { source: "residual-encoding", target: "filter-noise", relation: "defines" },
];

export function literatureGraph(): SheafGraph {
  return buildGraph(
    "literature",
    "Sheaf knowledge lattice",
    "Literature-grounded cellular sheaf",
    "Nodes and restriction maps drawn from Hansen–Ghrist, Cobb–Gebhart, Neural Sheaf Diffusion, HiSP / HETSHEAF, coordination sheaves, and Bertin. Unknown stalks start noisy so diffusion has work to do.",
    LEVELS,
    N,
    E,
  );
}
